---

# Check Admin status

- name: Check if admin port 8444 is listening
  wait_for:
    port: 8444
    delay: 5
    timeout: 10
    msg: "Timeout waiting for 8444 to respond"
  register: port_check
  ignore_errors: yes


##  Create an esiadmin to replace defalut admin 
- name: read the esiadmin json file
  slurp:
    src: "/tmp/esiadmin.json"
  register: esiadmin_json_file_content

# - name: Print esiadmin_json_file_content
#   debug:
#     var: esiadmin_json_file_content['content'] | b64decode


- name: Check if esiadmin exist
  uri:
    url: "https://localhost:8444/api/v2.0/administrators/esiadmin"
    method: HEAD
    headers:
      Content-Type: "application/json"
    url_username: "{{ st_admin_username }}"
    url_password: "{{ st_admin_password }}"
    status_code: "200,404" # 200 Success 404 Not found 
    force_basic_auth: yes
    validate_certs: no
  register: check_esiadmin_response

- name: Print check esiadmin response
  debug:
    var: check_esiadmin_response.status


- name: create eaiadmin administrator
  uri:
    url: "https://localhost:8444/api/v2.0/administrators"
    method: POST
    body_format: json
    body: "{{ esiadmin_json_file_content['content'] | b64decode }}"
    headers:
      Content-Type: "application/json"
    url_username: "{{ st_admin_username }}"
    url_password: "{{ st_admin_password }}"
    status_code: "201,204"
    force_basic_auth: yes
    validate_certs: no
  register: api_admin_response
  when: check_esiadmin_response.status == 404

# update esiadmin when  exist
- name: Update esiadmin 
  uri:
    url: "https://localhost:8444/api/v2.0/administrators/esiadmin"
    method: PUT
    body_format: json
    body: "{{ esiadmin_json_file_content['content'] | b64decode }}"
    headers:
      Content-Type: "application/json"
    url_username: "{{ st_admin_username }}"
    url_password: "{{ st_admin_password }}"
    status_code: "201,204"
    force_basic_auth: yes
    validate_certs: no
  register: api_admin_response
  when: check_esiadmin_response.status != 404

- name: Print response from API
  debug:
    var: api_admin_response.status

# check esiadmin
- name: Check esiadmin
  ansible.builtin.uri:
    url: "https://localhost:8444/api/v2.0/administrators?loginName=esiadmin"
    method: GET
    headers:
      Content-Type: "application/json"
    url_username: "esiadmin"
    url_password: "{{ esiadmin_password }}"
    # url_username: "{{ st_admin_username }}"
    # url_password: "{{ st_admin_password }}"    
    status_code: "200"
    force_basic_auth: yes
    validate_certs: no    
  register: _result
  ignore_errors: True      
  until: _result.status == 200
  retries: 3
  delay: 60
  run_once: true

- name: Print _result
  debug:
    var:  _result
  run_once: true